# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
    -   id: no-commit-to-branch
        args: ["--branch", "master", "--branch", "main"]
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files

-   repo: https://github.com/pycqa/isort
    rev: "5.10.1"
    hooks:
    - id: isort
      types: [python]
      args: ["--profile", "black"]

-   repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
    -   id: black

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: "v0.961"
    hooks:
    -   id: mypy
        additional_dependencies: [numpy, pydantic, types-PyYAML, types-python-dateutil]

-   repo: https://github.com/PyCQA/flake8
    rev: "4.0.1"
    hooks:
    -   id: flake8
        types: [python]

-   repo: https://github.com/PyCQA/pydocstyle
    rev: '6.1.1'
    hooks:
    -   id: pydocstyle
        types: [python]
        files: "nciraspw/.*"
        args: ["--convention", "google", "--add-ignore", "D301"]
        additional_dependencies: [toml]
