# Create a code coverage report.

name: "coverage"

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

jobs:
  run:
    name: "Code coverage report."
    runs-on: ubuntu-latest

    steps:
    - name: "Check out the repo"
      uses: actions/checkout@v2

    - name: "Set up Python"
      uses: "actions/setup-python@v2"
      with:
        python-version: "3.10"

    - name: "Install dependencies"
      run: |
        python -m pip install tox

    - name: "Generate report"
      run: |
        tox -e coverage
        coverage report -m

    - name: "Upload Coverage to Codecov"
      env:
        CODECOV_TOKEN: ${{secrets.CODECOV_TOKEN}}
      uses: codecov/codecov-action@v3
